name: Deploy to CloudPanel VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: surepackltd.com
          username: surepackltdftp
          password: Lawal20249##
          server-dir: /home/surepackltd/htdocs/surepackltd.com/
          timeout: 60000 # Increased timeout
          protocol: ftp # Explicitly set protocol
          port: 21 # Explicitly set port
