name: Deploy to CloudPanel VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build

      - name: Deploy to VPS
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 194.164.76.97
          username: surepackltdftp
          password: 'Lawal20249##'
          local_path: "./*"
          remote_path: "/home/surepackltd/htdocs/surepackltd.com/"
          port: 22
          sftpArgs: "-o StrictHostKeyChecking=no"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            README.md
