name: Deploy to CloudPanel VPS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build

      - name: Clean Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: 194.164.76.97
          username: surepackltdftp
          password: 'Lawal20249##'
          port: 22
          script: |
            rm -rf /home/surepackltd/htdocs/surepackltd.com/*

      - name: Deploy to VPS
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 194.164.76.97
          username: surepackltdftp
          password: 'Lawal20249##'
          remote_path: '/home/surepackltd/htdocs/surepackltd.com/'
          port: 22
          sftpArgs: '-o StrictHostKeyChecking=no'
