name: Deploy to CloudPanel VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 194.164.76.97
          username: surepackltdftp
          password: Lawal20249##
          remote_path: /home/surepackltd/htdocs/surepackltd.com/public/
          port: 22
