name: Deploy to CloudPanel VPS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 194.164.76.97  # Using IP instead of domain
          username: surepackltdftp
          password: Lawal20249##
          server-dir: /home/surepackltd/htdocs/surepackltd.com/public/
          timeout: 120000        # 2 minutes timeout
          port: 21
          protocol: ftp
          log-level: verbose     # Detailed logging
          dangerous-clean-slate: false
          dry-run: false
          state-name: .ftp-deploy-sync-state.json
          retries: 5            # Number of retries
          retry-delay: 5000     # Delay between retries in milliseconds
